---
- name: Remove VM and vApp from vCloud Director
  hosts: localhost
  tasks:
    - name: Delete VM
      vcd_vapp_vm:
        target_vm_name: "{{ vm_name }}"
        target_vapp: "{{ vm_name }}-vapp"
        target_vdc: "{{ target_vdc | default('Ceph-Management-Cluster') }}"
        state: "absent"

    - name: Delete vApp
      vcd_vapp:
        vapp_name: "{{ vm_name }}-vapp"
        vdc: "{{ target_vdc | default('Ceph-Management-Cluster') }}"
        state: "absent"
