---
# Server configuration tasks
- name: Set hostname
  hostname:
    name: "{{ server_hostname }}"
    
- name: Update /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ server_ip }} {{ server_hostname }}"
    state: present
    
- name: Update system packages
  yum:
    name: "*"
    state: latest
    update_cache: yes
    
- name: Install basic packages
  yum:
    name: "{{ basic_packages }}"
    state: present
    
- name: Configure SELinux to permissive (for GitLab compatibility)
  selinux:
    policy: targeted
    state: permissive
    
- name: Start and enable firewall
  systemd:
    name: firewalld
    state: started
    enabled: yes
